apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Chart.Name }}-pv   # Name of the persistent volume
spec:
  capacity:
    storage: 1Gi  # Total storage capacity of the volume
  accessModes:
  - ReadWriteOnce  # Access modes (ReadWriteOnce, ReadOnlyMany, ReadWriteMany)
  persistentVolumeReclaimPolicy: Retain  # Reclaim policy (Retain, Recycle, Delete)
  storageClassName: standard  # Storage class name
  hostPath:
    path: /tmp  # Path on the host machine