apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Chart.Name }}-pvc  # Name of the persistent volume claim
spec:
  accessModes:
  - ReadWriteOnce  # Access modes (ReadWriteOnce, ReadOnlyMany, ReadWriteMany)
  resources:
    requests:
      storage: 1Gi  # Requested storage size
